package View;

import Controller.NhapKhoController;
import Model.NhapKhoModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class NhapKhoView extends javax.swing.JFrame {
    
    private String currentIDNCC;
    private String currentIDKho;
    private boolean isImportMode = true;
    
    private NhapKhoController controller = new NhapKhoController();
    
    private void jtbNhapKhoMouseClicked(java.awt.event.MouseEvent evt) {
        int row = jtbNhapKho.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn sản phẩm!");
            return;
        }

        try {
            int slThayDoi = Integer.parseInt(txtSoLuong.getText());
            String mauSac = jtbNhapKho.getValueAt(row, 1).toString();
            String size = jtbNhapKho.getValueAt(row, 2).toString();
            boolean success = false;

            if (isImportMode) {
            success = controller.addSoLuong(slThayDoi, currentIDNCC, currentIDKho, mauSac, size);
            } else {
                success = controller.subtractSoLuong(slThayDoi, currentIDNCC, currentIDKho, mauSac, size);
            }

            if (success) {
                String msg = isImportMode ? "Đã nhập thêm " : "Đã xuất kho ";
                JOptionPane.showMessageDialog(this, msg + slThayDoi + " sản phẩm!");
                loadDataToTable();
            } else {
                String errorMsg = isImportMode ? "Lỗi cập nhật!" : "Lỗi! Số lượng xuất vượt quá tồn kho.";
                JOptionPane.showMessageDialog(this, errorMsg, "Lỗi", JOptionPane.ERROR_MESSAGE);
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Số lượng phải là số nguyên!");
        }
    }
    
    public NhapKhoView(String idNCC, String idKho, boolean isImportMode) {
        initComponents();

        this.currentIDNCC = idNCC;
        this.currentIDKho = idKho;
        this.isImportMode = isImportMode;

        loadDataToTable();
        this.setLocationRelativeTo(null);
    }

    public void loadDataToTable() {
        DefaultTableModel model = (DefaultTableModel) jtbNhapKho.getModel();
        model.setRowCount(0);

        java.util.List<NhapKhoModel> list = controller.getSanPhamTheoID(currentIDNCC, currentIDKho);
        for (NhapKhoModel sp : list) {
            model.addRow(new Object[]{
                sp.getTen_SP(), sp.getMauSac(), sp.getSize(), sp.getSoLuong(), sp.getTang(), sp.getKe()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtbNhapKho = new javax.swing.JTable();
        jbtThem = new javax.swing.JButton();
        jbtHuy = new javax.swing.JButton();
        jbtThoat = new javax.swing.JButton();
        jlbTang = new javax.swing.JLabel();
        jlbMauSac = new javax.swing.JLabel();
        jlbKe = new javax.swing.JLabel();
        jlbSize = new javax.swing.JLabel();
        jlbSoLuong = new javax.swing.JLabel();
        txtKe = new javax.swing.JTextField();
        txtSize = new javax.swing.JTextField();
        txtMauSac = new javax.swing.JTextField();
        txtSoLuong = new javax.swing.JTextField();
        txtTang = new javax.swing.JTextField();
        jbtThemMoi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jtbNhapKho.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Tên sản phẩm", "Màu sắc", "Size", "Số lượng", "Tầng", "Kệ"
            }
        ));
        jScrollPane1.setViewportView(jtbNhapKho);

        jbtThem.setText("Nhập/Xuất");
        jbtThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtThemActionPerformed(evt);
            }
        });

        jbtHuy.setText("Huỷ");
        jbtHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtHuyActionPerformed(evt);
            }
        });

        jbtThoat.setText("Thoát");
        jbtThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtThoatActionPerformed(evt);
            }
        });

        jlbTang.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlbTang.setText("Tầng");

        jlbMauSac.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlbMauSac.setText("Màu sắc");

        jlbKe.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlbKe.setText("Kệ");

        jlbSize.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlbSize.setText("Size");

        jlbSoLuong.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlbSoLuong.setText("Số lượng");

        txtKe.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        txtSize.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        txtMauSac.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        txtSoLuong.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        txtTang.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jbtThemMoi.setText("Thêm mới");
        jbtThemMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtThemMoiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtHuy)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbtThem)
                                .addGap(61, 61, 61)
                                .addComponent(jbtThemMoi))
                            .addComponent(jbtThoat))
                        .addGap(83, 83, 83)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlbMauSac)
                            .addComponent(jlbSize, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSize, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMauSac, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlbSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbTang, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbKe, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtKe, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTang, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 778, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(jbtHuy))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jbtThem)
                                    .addComponent(jbtThemMoi)
                                    .addComponent(jlbSoLuong)
                                    .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jlbMauSac)
                                    .addComponent(txtMauSac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jbtThoat))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jlbTang)
                                        .addComponent(txtTang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jlbSize)
                                        .addComponent(txtSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jlbKe)
                                    .addComponent(txtKe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtHuyActionPerformed
        txtMauSac.setText("");
        txtSoLuong.setText("");
        txtKe.setText("");
        txtSize.setText("");
        txtTang.setText("");
    }//GEN-LAST:event_jbtHuyActionPerformed

    private void jbtThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtThemActionPerformed
        int row = jtbNhapKho.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn sản phẩm!");
            return;
        }

        try {
            int slThayDoi = Integer.parseInt(txtSoLuong.getText());
            String mauSac = jtbNhapKho.getValueAt(row, 1).toString();
            String size = jtbNhapKho.getValueAt(row, 2).toString();
            boolean success = false;

            if (isImportMode) {
                success = controller.addSoLuong(slThayDoi, currentIDNCC, currentIDKho, mauSac, size);
            } else {
                // Gọi hàm subtractSanPham (hoặc subtractSoLuong) bạn đã thêm
                success = controller.subtractSoLuong(slThayDoi, currentIDNCC, currentIDKho, mauSac, size);
            }

            if (success) {
                String msg = isImportMode ? "Đã nhập thêm " : "Đã xuất kho ";
                JOptionPane.showMessageDialog(this, msg + slThayDoi + " sản phẩm!");
                loadDataToTable();
            } else {
                String errorMsg = isImportMode ? "Lỗi cập nhật!" : "Lỗi! Số lượng xuất vượt quá tồn kho.";
                JOptionPane.showMessageDialog(this, errorMsg, "Lỗi", JOptionPane.ERROR_MESSAGE);
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Số lượng phải là số nguyên!");
        }
    }//GEN-LAST:event_jbtThemActionPerformed

    private void jbtThemMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtThemMoiActionPerformed
        ThemMoiView themMoi = new ThemMoiView(currentIDNCC, currentIDKho);
        themMoi.setVisible(true);
        themMoi.setLocationRelativeTo(null); 

        themMoi.addWindowListener(new java.awt.event.WindowAdapter() {
        @Override
        public void windowClosed(java.awt.event.WindowEvent e) {
            loadDataToTable();
        }
    });
    }//GEN-LAST:event_jbtThemMoiActionPerformed

    private void jbtThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtThoatActionPerformed
        this.dispose();
    }//GEN-LAST:event_jbtThoatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NhapKhoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NhapKhoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NhapKhoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NhapKhoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NhapKhoView("KH001", "A01", true).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtHuy;
    private javax.swing.JButton jbtThem;
    private javax.swing.JButton jbtThemMoi;
    private javax.swing.JButton jbtThoat;
    private javax.swing.JLabel jlbKe;
    private javax.swing.JLabel jlbMauSac;
    private javax.swing.JLabel jlbSize;
    private javax.swing.JLabel jlbSoLuong;
    private javax.swing.JLabel jlbTang;
    private javax.swing.JTable jtbNhapKho;
    private javax.swing.JTextField txtKe;
    private javax.swing.JTextField txtMauSac;
    private javax.swing.JTextField txtSize;
    private javax.swing.JTextField txtSoLuong;
    private javax.swing.JTextField txtTang;
    // End of variables declaration//GEN-END:variables
}
